### ISSUE TITLE
The published version of this package on npm has a peer dep on svelte v5 which is not released.

### ISSUE THREAD

**Issue by oliverabrahams** [Mitcheljager/svelte-confetti#13] opened 2024-08-08 14:46 UTC
When installing version https://www.npmjs.com/package/svelte-confetti v2.1.1  PNPM gives this error ->

ERR_PNPM_NO_MATCHING_VERSION  No matching version found for svelte@>=5.0.0 <6.0.0

The package json version on main is "version": "1.4.0"  but on npm there is a v2.1.1

**Comment by soerenmeier** [comment] 2024-08-15 20:09
The issue is this line:
https://github.com/Mitcheljager/svelte-confetti/blob/8677b2ac60b36a138921d8488545d52460ece214/package.json#L28

I was able to fix it by using `--legacy-peer-deps` in npm. Maybe that works for pnpm as well.

**Comment by Mitcheljager** [comment] 2024-08-15 20:45
If you are using Svelte 4, use version 1.x.x. Version 2.x.x is reserved for Svelte 5.

**Comment by Mitcheljager** [comment] 2024-08-15 21:48
I might have used the wrong version, using `^5.0.0` instead of `>=5.0.0`. Not entirely sure, but let me know if this still happens with the Svelte 5 branch

**Comment by peterolson** [comment] 2024-08-17 02:43
@Mitcheljager Still happening

> npm install svelte-confetti@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: extensive-reading-front-end@0.0.1
npm ERR! Found: svelte@5.0.0-next.223
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.0-next.223" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@">=5.0.0" from svelte-confetti@2.1.2
npm ERR! node_modules/svelte-confetti
npm ERR!   svelte-confetti@"2.1.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by rikardkling** [comment] 2024-08-27 07:39
Same here ☝️

**Comment by Rar9** [comment] 2024-09-22 05:12
Please fix for is not official stable svelte 4

**Comment by bigandy** [comment] 2024-09-25 09:06
@Mitcheljager I think you might need to change the svelte peerDependencies to `^5.0.0-next.190` or a next release version currently it is 259 [see svelte releases](https://github.com/sveltejs/svelte/releases) as this is what [Astro's svelte package does](https://github.com/withastro/astro/blob/next/packages/integrations/svelte/package.json#L64)

**Comment by Mitcheljager** [comment] 2024-12-08 19:44
This should now be good with the Svelte 5 release

**Closed by Mitcheljager** 2024-12-08 19:44 UTC
